"""initial tables

Revision ID: 740c48b732dc
Revises: 
Create Date: 2026-07-29 09:34:33.838316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740c48b732dc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('source_code', sa.Text(), nullable=False),
    sa.Column('parsed_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_code_submissions_user_id'), 'code_submissions', ['user_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_language'), 'knowledge_chunks', ['language'], unique=False)
    op.create_table('test_generation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('generated_tests', sa.Text(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['code_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_generation_results_submission_id'), 'test_generation_results', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_generation_results_submission_id'), table_name='test_generation_results')
    op.drop_table('test_generation_results')
    op.drop_index(op.f('ix_knowledge_chunks_language'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_code_submissions_user_id'), table_name='code_submissions')
    op.drop_table('code_submissions')
    # ### end Alembic commands ###
